### ISSUE TITLE
Returned message: ==>Detected Windows 32-Bit. In order to work properly use ATMMalScan32.exe

### ISSUE THREAD

**Issue by talesgouveia** [fboldewin/ATMMalScan#1]
Hello,

What can be causing it behavior?

I am trying to run ATMMalScan32.exe in Win 7 32 bit environment.
However always, even using a Win 7 32 bit environment, this message is being returned: 
==>Detected Windows 32-Bit. In order to work properly use ATMMalScan32.exe

Attached is the image to ilustrate: 

![image](https://user-images.githubusercontent.com/18128343/105386166-d6452100-5bf2-11eb-8668-d2a3a3c25f31.png)

**Comment by fboldewin** [comment]
Fixed in v0.2
